### ISSUE TITLE
支持播放flac

### ISSUE THREAD

**Issue by TheWanderingCoel** [sunzongzheng/music#104]
大佬好,目前好像只能播放mp3一类的,点击播放本地的flac无反应,请问大佬有没有意愿支持flac呢?

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/69838116-0ca43c00-128d-11ea-8480-96aa313ee76a.png)
我这边测试播放是正常的，能否提供一下flac文件？ape是不支持的，flac支持

**Comment by TheWanderingCoel** [comment]
![WX20191129-094734](https://user-images.githubusercontent.com/39617891/69838173-5d1b9980-128d-11ea-8dba-ec3ff6e2694e.png)
我这里一直卡着不动,flac是从网易云下的

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/69838333-19755f80-128e-11ea-948c-8346f656b951.png)
我试了这两首都是可以的，还是提供一下flac文件把。

可以f12或进设置打开控制台看看有没有报错，卡主很可能是有报错

**Comment by TheWanderingCoel** [comment]
flac有点太大了,github上传不上来...
![WX20191129-095734](https://user-images.githubusercontent.com/39617891/69838484-b1734900-128e-11ea-83b9-0320e337f83d.png)
这是中文

**Comment by TheWanderingCoel** [comment]
![WX20191129-095939](https://user-images.githubusercontent.com/39617891/69838543-fb5c2f00-128e-11ea-9dd6-8a240d06bfd6.png)

**Comment by sunzongzheng** [comment]
是最新代码自行打包的还是下载的release里的？

**Comment by TheWanderingCoel** [comment]
release的1.2.0版本

**Comment by sunzongzheng** [comment]
最新代码解决了，需自行打包。

报错的原因是文件的码率不符合128k、320k、999k的任何一个，目前的做法是直接显示文件的码率，但我忘了做取整操作，现在会有小数位，像我上面截图的那样

**Comment by TheWanderingCoel** [comment]
好的,谢谢。十分感谢作者~

**Comment by TheWanderingCoel** [comment]
作者大大,能否问下这个打包报错是为什么呢？
```
Coel-Wu:music thewanderingcoel$ npm run build

> player@1.2.0 build /Users/thewanderingcoel/Desktop/music
> node .electron-vue/build.js && electron-builder

 ___              __                        __                       ___       __    
/\_ \       __   /\ \__     ____           /\ \       __  __   __   /\_ \     /\ \   
\//\ \    / ,.`\ \ \ ,_\   / ,__\  _______ \ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \  
  \_\ \_ /\  __/  \ \ \/  /\__, `\/\______\ \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \ 
  /\____\\ \____\  \ \ \_ \/\____/\/______/  \ \____/ \ \____/ \ \ \  /\____\\ \____\
  \/____/ \/____/   \ \__\ \/___/             \/___/   \/___/   \/_/  \/____/ \/___ /
                     \/__/                                                           

  \ building main process
  / building main process
  / building renderer process
  / building background process

   ERROR  failed to build background process

    Hash: 1d3a63a20c6a2d77ea1a
    Version: webpack 4.41.2
    Time: 9879ms
    Built at: 11/29/2019 11:16:11 AM
                                 Asset     Size  Chunks               Chunk Names
    background.1d3a63a20c6a2d77ea1a.js  225 KiB       0  [immutable]  background
    Entrypoint background = background.1d3a63a20c6a2d77ea1a.js
     [0] ./node_modules/@babel/runtime/helpers/defineProperty.js 289 bytes {0} [built]
     [1] external "electron" 42 bytes {0} [built]
     [3] ./node_modules/vue/dist/vue.esm.js 318 KiB {0} [built]
     [4] ./src/background/macStatusBarLyric/eventBus.js 25 bytes {0} [built]
     [5] ./node_modules/@babel/runtime/regenerator/index.js 49 bytes {0} [built]
     [7] ./node_modules/@babel/runtime/helpers/asyncToGenerator.js 809 bytes {0} [built]
    [12] external "vue-router" 42 bytes {0} [built]
    [13] ./src/background/App.vue 248 bytes {0} [built] [failed] [1 error]
    [14] external "element-ui" 42 bytes {0} [built]
    [15] ./src/background/desktopLyric/index.vue 248 bytes {0} [built] [failed] [1 error]
    [16] ./src/background/components/icon/index.vue 248 bytes {0} [built] [failed] [1 error]
    [17] ./src/renderer/assets/iconfont.js 106 KiB {0} [built]
    [21] ./src/background/main.js + 14 modules 16.9 KiB {0} [built]
         | ./src/background/main.js 535 bytes [built]
         | ./src/background/router/index.js 210 bytes [built]
         | ./src/background/components/index.js 174 bytes [built]
         | ./src/background/macStatusBarLyric/index.js 4.05 KiB [built]
         | ./src/background/macStatusBarLyric/canvas.class.js 1.03 KiB [built]
         | ./src/background/macStatusBarLyric/lyrics.class.js 3.44 KiB [built]
         | ./src/background/macStatusBarLyric/control.class.js 3.25 KiB [built]
         | ./src/background/macStatusBarLyric/assets/skip_previous.png 547 bytes [built]
         | ./src/background/macStatusBarLyric/assets/tray-last-white.png 671 bytes [built]
         | ./src/background/macStatusBarLyric/assets/play_arrow.png 511 bytes [built]
         | ./src/background/macStatusBarLyric/assets/tray-play-white.png 575 bytes [built]
         | ./src/background/macStatusBarLyric/assets/skip_next.png 551 bytes [built]
         | ./src/background/macStatusBarLyric/assets/tray-next-white.png 671 bytes [built]
         | ./src/background/macStatusBarLyric/assets/pause.png 359 bytes [built]
         | ./src/background/macStatusBarLyric/assets/tray-pause-white.png 383 bytes [built]
    [23] ./node_modules/css-loader/dist/cjs.js!./node_modules/element-ui/lib/theme-chalk/index.css 192 KiB [built]
    [28] ./node_modules/style-loader/lib/addStyles.js 8.5 KiB [built]
        + 15 hidden modules
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
    
    ERROR in ./node_modules/element-ui/lib/theme-chalk/index.css
    Module build failed (from ./node_modules/css-loader/dist/cjs.js):
    ModuleBuildError: Module build failed (from ./node_modules/url-loader/dist/cjs.js):
    TypeError: Cannot read property 'fileLoader' of undefined
        at Object.module.exports (/Users/thewanderingcoel/Desktop/music/node_modules/file-loader/index.js:14:28)
        at Object.loader (/Users/thewanderingcoel/Desktop/music/node_modules/url-loader/dist/index.js:73:19)
        at /Users/thewanderingcoel/Desktop/music/node_modules/webpack/lib/NormalModule.js:316:20
        at /Users/thewanderingcoel/Desktop/music/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /Users/thewanderingcoel/Desktop/music/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        at runSyncOrAsync (/Users/thewanderingcoel/Desktop/music/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
        at iterateNormalLoaders (/Users/thewanderingcoel/Desktop/music/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
        at /Users/thewanderingcoel/Desktop/music/node_modules/loader-runner/lib/LoaderRunner.js:205:4
        at /Users/thewanderingcoel/Desktop/music/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
     @ ./node_modules/element-ui/lib/theme-chalk/index.css
    
    ERROR in ./node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf
    Module build failed (from ./node_modules/url-loader/dist/cjs.js):
    TypeError: Cannot read property 'fileLoader' of undefined
        at Object.module.exports (/Users/thewanderingcoel/Desktop/music/node_modules/file-loader/index.js:14:28)
        at Object.loader (/Users/thewanderingcoel/Desktop/music/node_modules/url-loader/dist/index.js:73:19)
     @ ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader/dist/cjs.js!./node_modules/element-ui/lib/theme-chalk/index.css) 5:38-74
     @ ./node_modules/element-ui/lib/theme-chalk/index.css
    
    ERROR in ./src/background/App.vue
    Module build failed (from ./node_modules/vue-loader/index.js):
    TypeError: Cannot read property 'vue' of undefined
        at Object.module.exports (/Users/thewanderingcoel/Desktop/music/node_modules/vue-loader/lib/loader.js:52:48)
     @ ./src/background/main.js 3:0-28 16:9-12
    
    ERROR in ./src/background/components/icon/index.vue
    Module build failed (from ./node_modules/vue-loader/index.js):
    TypeError: Cannot read property 'vue' of undefined
        at Object.module.exports (/Users/thewanderingcoel/Desktop/music/node_modules/vue-loader/lib/loader.js:52:48)
     @ ./src/background/components/index.js 3:10-37
     @ ./src/background/main.js
    
    ERROR in ./src/background/desktopLyric/index.vue
    Module build failed (from ./node_modules/vue-loader/index.js):
    TypeError: Cannot read property 'vue' of undefined
        at Object.module.exports (/Users/thewanderingcoel/Desktop/music/node_modules/vue-loader/lib/loader.js:52:48)
     @ ./src/background/router/index.js 7:15-51
     @ ./src/background/main.js
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/dist/cjs.js!node_modules/element-ui/lib/theme-chalk/index.css:
        Entrypoint undefined = extract-text-webpack-plugin-output-filename
        [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/element-ui/lib/theme-chalk/index.css 192 KiB {0} [built]
        [1] ./node_modules/css-loader/dist/runtime/api.js 2.61 KiB {0} [built]
        [2] ./node_modules/css-loader/dist/runtime/getUrl.js 626 bytes {0} [built]
        [3] ./node_modules/element-ui/lib/theme-chalk/fonts/element-icons.woff 8.07 KiB {0} [built]
        [4] ./node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf 360 bytes {0} [built] [failed] [1 error]
        
        ERROR in ./node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf
        Module build failed (from ./node_modules/url-loader/dist/cjs.js):
        TypeError: Cannot read property 'fileLoader' of undefined
            at Object.module.exports (/Users/thewanderingcoel/Desktop/music/node_modules/file-loader/index.js:14:28)
            at Object.loader (/Users/thewanderingcoel/Desktop/music/node_modules/url-loader/dist/index.js:73:19)
         @ ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader/dist/cjs.js!./node_modules/element-ui/lib/theme-chalk/index.css) 5:38-74
    Child html-webpack-plugin for "background.html":
                  Asset     Size  Chunks  Chunk Names
        background.html  535 KiB       0  
        Entrypoint undefined = background.html
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 2.55 KiB {0} [built]
        [1] ./node_modules/lodash/lodash.js 528 KiB {0} [built]
        [2] (webpack)/buildin/module.js 497 bytes {0} [built]
```

**Comment by sunzongzheng** [comment]
你手动升级了webpack版本？
https://github.com/sunzongzheng/music/blob/382b0d15bd2730227366878ab9a3632bd5b831ad/package.json#L137

**Comment by TheWanderingCoel** [comment]
我降级nodejs到v8,编译成功了,现在可以播放了,谢谢大佬。
